
FROM node:20-alpine3.17

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./

# Install dependencies including dev dependencies
RUN npm install

# Bundle app source
COPY . .

# Expose port 3000
EXPOSE 3000

# Run the app
CMD [ "npm", "run", "start" ]